import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./index.scss";
import "./home.scss";
import "./auth.scss";
import "./components.scss";
import "./profile.scss";
import "./payments.scss";

import DataProvider from "@/context/DataContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <meta name="theme-color" content="#000000"></meta>
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link href="/logo.png" rel="icon" type="image/png" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Source+Serif+4:ital,opsz,wght@0,8..60,200..900;1,8..60,200..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <DataProvider>
        <body className={inter.className}>
          {children}
          <div id="overlay" className="hidden"></div>
        </body>
      </DataProvider>
    </html>
  );
}
